In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.python.ops.rnn_cell_impl import _zero_state_tensors
tf.enable_eager_execution()

In [ ]:
class customRNNcell(tf.contrib.rnn.RNNCell):
    def __init__(self, input_dim):
        self.input_dim = input_dim

        self.W = tf.get_variable("W", [self.input_dim , 1], tf.float32)
        self.b = tf.get_variable("b", [1])

    @property
    def state_size(self):
        return 1

    @property
    def output_size(self):
        return 1

    def __call__(self, inputs, state):
        output =state*tf.nn.sigmoid(tf.matmul(inputs, self.W)+ self.b)

        return output, output

In [ ]:
def CapRnnModel(input_tensor, initial_tensor):

    cap_cell = customRNNcell(input_dim=5)
    cap_series, final_cap = tf.nn.dynamic_rnn(cell=cap_cell, inputs=input_tensor, initial_state=initial_tensor)

    return  cap_series , final_cap

x_place=tf.placeholder(tf.float32 , [1,2,3,4,5])
init_cap_place=tf.placeholder(tf.float32 , [1,1])

y=CapRnnModel(x_place, init_cap_place)

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    a=np.random.rand(1,2,3)
    b=np.random.rand(1,1)
    result=sess.run(y,feed_dict={x_place:a , init_cap_place:b})
    print(result)

In [ ]:
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(3)

In [ ]:
rnn_cell.weights
init_state=rnn_cell.zero_state(12,dtype=tf.float32)


In [12]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])

In [14]:
tf.slice(t, [1, 0, 0], [1, 1, 3])

<tf.Tensor: id=29, shape=(1, 1, 3), dtype=int32, numpy=array([[[3, 3, 3]]], dtype=int32)>

In [15]:
t.shape

TensorShape([Dimension(3), Dimension(2), Dimension(3)])

In [52]:
t1=tf.constant(tf.transpose([1,2,3,4,5,6,7,8,9]),shape=[9,1])

In [50]:
t2=tf.slice(t1,[6,0],[3,1])
t2

<tf.Tensor: id=128, shape=(3, 1), dtype=int32, numpy=
array([[7],
       [8],
       [9]], dtype=int32)>

In [54]:
tf.concat([t1,t2],0)

<tf.Tensor: id=153, shape=(12, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [7],
       [8],
       [9]], dtype=int32)>

In [33]:
tf.slice(t2,[0,2],[2,1])

<tf.Tensor: id=71, shape=(2, 1), dtype=int32, numpy=
array([[3],
       [6]], dtype=int32)>

In [36]:
t1 = [[1], [2], [3]]

In [37]:
t2 = [[4], [5], [6]]

In [55]:
tf.concat([t1,t2],1)
t(t2)

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [9,1] vs. shape[1] = [3,1] [Op:ConcatV2] name: concat

In [ ]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.python.ops.rnn_cell_impl import _zero_state_tensors

class CapRNNcell(tf.contrib.rnn.RNNCell):
    def __init__(self, input_dim):
        self.input_dim = input_dim

        self.W = tf.get_variable("W", [self.input_dim , 1], tf.float32)
        self.b = tf.get_variable("b", [1])

    @property
    def state_size(self):
        return 1

    @property
    def output_size(self):
        return 1

    def __call__(self, inputs, state):
        output =state*tf.nn.sigmoid(tf.matmul(inputs, self.W)+ self.b)

        return output, output

def CapRnnModel(timeSeries_before_forgetting_gate, init_cap):

    cap_cell = CapRNNcell(input_dim=3)
    cap_series, final_cap = tf.nn.dynamic_rnn(cell=cap_cell, inputs=timeSeries_before_forgetting_gate, initial_state=init_cap)

    return  cap_series , final_cap

x_place=tf.placeholder(tf.float32 , [1,2,3])
init_cap_place=tf.placeholder(tf.float32 , [1,1])

y=CapRnnModel(x_place, init_cap_place)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    a=np.random.rand(1,2,3)
    b=np.random.rand(1,1)
    result=sess.run(y,feed_dict={x_place:a , init_cap_place:b})
    print(result)

In [56]:
timesteps=1000
num_input=1
batch_size=1
batch_x=spike_rec=tf.where(tf.greater(tf.random_uniform(shape=[batch_size,num_input,timesteps]),0.5),
                  tf.constant(1.0,shape=[batch_size,num_input,timesteps],dtype=tf.float32),
                              tf.constant(0.0,shape=[batch_size,num_input,timesteps],dtype=tf.float32))

In [57]:
batch_x

<tf.Tensor: id=171, shape=(1, 1, 1000), dtype=float32, numpy=
array([[[1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
         0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
         1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
         0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
         1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1.,
         0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
         0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
         0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
         0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
         0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
         0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
         0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0