In [2]:
from __future__ import print_function
import tensorflow as tf
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline 
tf.enable_eager_execution()
import itertools

In [ ]:
w=tf.constant([[1,0,1],[0,1,0],[1,1,0]],dtype=tf.float32)

In [ ]:
h=tf.matmul(b,w)

In [ ]:
h=tf.reshape(h,[-1,3,3])

In [ ]:

tf.matrix_set_diag(a, tf.zeros(a.shape[0:-1]), name=None)

In [ ]:
embed = tf.reshape(embed, [-1, m])
h = tf.matmul(embed, U)
h = tf.reshape(h, [-1, n, c])


In [ ]:
def _tensor_linear_rec_in(x,y,output_size):
    """input - x : a 3D tensor with batch x n x n 
    y is a 2D with size batch x m
    outputs a tensor  with size batch x output_size
    """ 
    shape_x=x.get_shape()
    shape_y=y.get_shape()
    # 
    scope=vs.get_variable_scope()
    with vs.variable_scope(scope) as outer_scope:
#        weight_rec=tf.get_variable(_RECURRENT_WEIGHT_NAME,[shape_x[1],shape_x[2]],
#                                   initializer=tf.constant(1.0,shape=[shape_x[1],shape_x[2]])) # [n x n]
#        weight_in=tf.get_variable(_INPUT_WEIGHT_NAME,[shape_y[1],shape_y[2]],
#                                  initializer=tf.constant(0.0,shape=[shape_y[1],shape_y[2]])) # [n x m]
        weight_rec=tf.get_variable(_RECURRENT_WEIGHT_NAME,
                                   initializer=tf.constant(0.0,shape=[shape_x[1],shape_x[2]])) # [n x n]
        weight_in=tf.get_variable(_INPUT_WEIGHT_NAME,
                                  initializer=tf.constant(.5,shape=[shape_y[1],shape_y[2]])) # [n x m]

        #
        # apply_weights 
        #recurrent
        res_rec_aux=tf.multiply(x,weight_rec)
        res_rec_final=tf.reduce_sum(res_rec_aux,tf.rank(res_rec_aux)-1)
        #input
        res_in_aux=tf.multiply(y,weight_in)
        res_in_final=tf.reduce_sum(res_in_aux,tf.rank(res_in_aux)-1)
        # sum both 
        res=tf.add(res_in_final,res_rec_final)

        return res

_INPUT_WEIGHT_NAME = "W_in"
_RECURRENT_WEIGHT_NAME = "W_rec"

In [ ]:
a = tf.constant(np.arange(1.0, 33.0, dtype=np.int32),
                shape=[2, 4, 4],dtype=tf.float32)
b = tf.constant(np.arange(1.0, 25.0, dtype=np.int32),
                shape=[2, 4, 3],dtype=tf.float32)


In [ ]:
a

In [ ]:
tf.reduce_sum(b,tf.rank(b)-1)

In [ ]:
_tensor_linear_rec_in(a,b,4)

In [ ]:
def foo():
  with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
    v = tf.get_variable("v", [1])
  return v

v1 = foo()  # Creates v.
v2 = foo()  # Gets the same, existing v.
assert v1 == v2

In [ ]:
w=tf.constant([[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[.5,.5,.5,.5],[.5,.5,.5,.5]])

In [ ]:
w1=tf.constant([[1.0,1.0,1.0],[1.0,1.0,1.0],[.5,.5,.5],[.5,.5,.5]])

In [ ]:
c=tf.multiply(a,w)


In [ ]:
def _tensor_expand_dim(x,y,output_size):
    """input - x : a 2D tensor with batch x n 
    y is a 2D with size batch x m
    outputs is 3D tensor with size batch x n x n and batch x n x m 
    """ 
    shape_x=x.get_shape()
    shape_y=y.get_shape()
    # define a matrix for removing the diagonal in recurrent spikes 
    x_diag_fixer=tf.get_variable('x_diag_fixer',
                                 initializer=tf.subtract(tf.constant(1.0,shape=[shape_x[1],shape_x[1]]),
                                                    tf.eye(output_size))) # [n x n]
    # expand x  
    x_temp=tf.reshape(tf.tile(x,[1,output_size]),[-1,output_size,shape_x[1]])
    # remove diagonal 
    x_expand=tf.multiply(x_temp,x_diag_fixer)
    # expand y  
    y_expand=tf.reshape(tf.tile(y,[1,output_size]),[-1,output_size,shape_y[1]])


    return x_expand, y_expand


In [ ]:
a=tf.constant([[1,0,0],[0,1,1],[0,0,1],[1,1,0]],dtype=tf.float32)

In [ ]:
a

In [ ]:
b=tf.constant([[1,0],[0,1],[0,0],[1,1]],dtype=tf.float32)
b

In [ ]:
a

In [ ]:
a_expand,b_expand=_tensor_expand_dim(a,b,3)

In [ ]:
a_expand

In [ ]:
x_diag_fixer=tf.get_variable('x_diag_fixer',initializer=tf.subtract(tf.constant(1.0,shape=[3,3]),
                                                    tf.eye(3))) # [n x n]


In [ ]:
test=x_diag_fixer.get_shape()

In [ ]:
np.array([2,2])

In [ ]:
tf.greater_equal(a,1.0)

In [ ]:
input_spikes=np.random.randint(2,size=[2,10,2])

In [ ]:
input_spikes

In [ ]:
input_spikes=np.random.randint(2,size=[2,10,1])

In [ ]:
input_spikes.shape

In [ ]:
tf_input_values = tf.constant(input_spikes, dtype=tf.float32)

In [ ]:
inputs=tf.random_uniform([batch_size,num_of_inputs])
batch_size=10
num_of_inputs=1
inputs=tf.random_uniform([batch_size,num_of_inputs])
shape_x=np.array([batch_size,num_of_inputs])
threshold_size=5
weight=tf.concat([tf.constant(1.0,shape=[shape_x[0],threshold_size]),
                                                              tf.constant(-1.0,shape=[shape_x[0],threshold_size])],
                                                                axis=1
                                                               )
threshold=tf.constant([.2,.4,.6,.8,1],shape=[1,5])

In [ ]:
threshold=tf.constant([.2,.4,.6,.8,1],shape=[1,5])

In [ ]:
threshold_expand=tf.matmul(tf.constant(1.0,shape=[shape_x[0],1]),threshold)
threshold_expand

do positive crossing first 

In [ ]:
inputs_expand=tf.matmul(inputs,tf.constant(1.0,shape=[shape_x[1],threshold_size]))


In [ ]:
inputs

In [ ]:
positive_outputs=tf.cast(tf.greater(inputs_expand-threshold_expand,0),tf.float32)

In [ ]:
positive_outputs

In [ ]:
negative_outputs=tf.cast(tf.greater(threshold_expand-inputs_expand,0),tf.float32)

In [ ]:
negative_outputs 

In [ ]:
tf.concat([positive_outputs,negative_outputs],axis=1)

In [ ]:
np.divide(1,40)

In [ ]:
a=np.linspace(np.divide(1,40),1,40)

In [ ]:
tf.constant(tf.linspace(1.0,2,2),shape=[1,40])

In [ ]:
a=tf.random_uniform(shape=[10,1],dtype=tf.float32)
a

In [ ]:
def _calcualte_crossings(x,threshold):
    """input :x : a 2D tensor with batch x n 
    outputs a tensor with the same size as x 
    and values of 0 or 1 depending on comparison between 
    x and threshold""" 
    @tf.custom_gradient
    def crossings(x):
        dtype=x.dtype
        shape=x.get_shape()
        thresholds=tf.constant(threshold,shape=[shape[0].value,shape[1].value],dtype=dtype)
        # if it has one row 
        res=tf.greater_equal(x,thresholds)
        def grad(dy):
            # calculate 1-|x|
            temp=1-tf.abs(x)
            dyres=tf.maximum(temp,0.0)
            return dyres
        return tf.cast(res,dtype=dtype), grad
    z=crossings(x)
    return z 


In [ ]:
tf.set_random_seed(10)
a=tf.random_uniform(shape=[5,5],dtype=tf.float32)
threshold=tf.constant([.5,0,.1,.2,0],shape=[5,1])
a

In [ ]:
tf.negative(tf.divide(tf.sign(threshold-a)-1,2))

In [ ]:



import matplotlib.cm as cm
plt.figure(figsize=[15,10])
colors_map=cm.viridis(np.linspace(0,1,z.shape[0]))
for t in range(z.shape[1]):
    cross=np.argwhere(z[:,t])
    plt.scatter(cross*0+t,cross,color=colors_map[cross.flatten(),:],s=4)
    

In [ ]:
a = tf.constant([-1,1],dtype=tf.float32)
b = tf.nn.relu(a)
g = tf.gradients(b, a)

In [ ]:
with tf.Session() as sess:
    tf.global_variables_initializer()
    c=sess.run(g)
    


In [ ]:
g=tf.constant(np.ones(4,3))

In [ ]:
a=np.arange(12).reshape(4,3)
b=np.arange(8).reshape(4,-1)
c=np.arange(24).reshape(4,3,2)


In [ ]:
a=tf.constant(np.arange(10.0),shape=[2,5])


In [ ]:
b=tf.constant(np.arange(6.0), shape=[2,3])


In [ ]:
result = tf.einsum("un,uv->unv", a, b)
result

In [ ]:
batch=2
n=3
m=4
a=tf.constant(np.arange(6.0),shape=[batch,n])


In [ ]:
b=tf.constant(np.arange(24.0),shape=[batch,n,m])
b

In [ ]:
tf.multiply(b,tf.expand_dims(a,axis=-1))

In [ ]:
c=tf.expand_dims(tf.expand_dims(b,axis=0),axis=-1)

In [ ]:
c

use itertools and dictionary to create a loop over differet parameters 


In [ ]:
dict_train_step={"A":10,"B":100,"C":1000}
dict_batch_size={"A":50,"B":150,"C":250}

In [ ]:
a=list(itertools.permutations('ABC', 2))

In [ ]:
dict_train_step[a[0][1]]


In [ ]:
a=tf.constant()


In [ ]:
b=tf.constant(np.arange(24.0),shape=[batch,n,m])

In [ ]:
batch=2
n=3
m=4
a=tf.constant(np.arange(6.0),shape=[batch,n])


In [ ]:
a

In [ ]:
tf.transpose(a)

In [ ]:
a=tf.constant(np.arange(18.0),shape=[3,3,2],dtype=tf.float32)
a

In [ ]:
b=tf.roll(a,shift=-1, axis=1)
b

In [ ]:
b[:,-0,:]

In [ ]:
c=tf.expand_dims(tf.concat([tf.ones([2,2],tf.float32),tf.zeros([1,2],dtype=tf.float32)],axis=0),axis=0)
c

In [ ]:
tf.multiply(a,c)


In [8]:
b=tf.constant(np.array([1,3,1]),dtype=tf.int32)
batch_size=2
tf.transpose(tf.one_hot(b,depth=max(b)+1))

<tf.Tensor: id=103, shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.]], dtype=float32)>

In [ ]:
c=tf.tile(tf.expand_dims(tf.transpose(tf.one_hot(b,depth=max(b)+1)),axis=0),[batch_size,1,1])
c

In [ ]:
a=tf.constant([[1,1,1],[0,0,1]],tf.float32)


In [ ]:
d=tf.multiply(tf.expand_dims(a,axis=-2),c)

In [ ]:
d


In [ ]:
S=tf.roll(d,shift=-1,axis=1)
S[:,0,:]
tf.constant(0,shape=[1,1])

In [ ]:
tf.diag(tf.concat([tf.ones(3,tf.float32),tf.constant([0],dtype=tf.float32)],axis=0))

In [4]:
num_hidden=2
num_batch=3
delay_vect=tf.random_uniform(minval=1,maxval=3,shape=[num_hidden],dtype=tf.int32)
delay_vect


<tf.Tensor: id=4, shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
spike=tf.cast(tf.random_uniform(minval=0,maxval=2,shape=[num_batch,num_hidden],dtype=tf.int32),tf.float32)
spike

In [ ]:
delay_mat=tf.transpose(tf.one_hot(delay_vect,depth=max(delay_vect)+1))
delay_mat

In [ ]:
delay_tensor=tf.tile(tf.expand_dims(delay_mat,axis=0),[num_batch,1,1])

In [ ]:
output_spike=tf.einsum('uvn,vn->uvn',delay_tensor,spike)
output_spike

In [ ]:

tf.multiply(tf.expand_dims(spike,axis=-2),delay_tensor)

In [ ]:
elems = tf.constant([1, 2, 3, 4, 5, 6],dtype=tf.int32)


In [23]:
spike=tf.random_uniform(minval=0,maxval=2,shape=[batch_size,num_hidden],dtype=tf.int32)
spike

<tf.Tensor: id=326, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 0]], dtype=int32)>

In [17]:
tf.multiply(tf.expand_dims(tf.cast(spike,tf.float32),axis=-1),tf.one_hot(spike,depth=3))

<tf.Tensor: id=235, shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 1., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [18]:
synaptic_delay=tf.constant([3,2])

In [24]:
tf.multiply(synaptic_delay,spike)

<tf.Tensor: id=340, shape=(2, 2), dtype=int32, numpy=
array([[0, 2],
       [3, 0]], dtype=int32)>

In [29]:
tf.multiply(tf.expand_dims(tf.cast(spike,tf.float32),axis=-2),tf.one_hot(tf.multiply(synaptic_delay,spike),depth=4,axis=1))

<tf.Tensor: id=442, shape=(2, 4, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]]], dtype=float32)>

In [31]:
synaptic_shape=np.array([1,2,3])
correction_mat=tf.expand_dims(tf.concat([tf.ones([synaptic_shape[1]-1,synaptic_shape[2]],tf.float32),tf.zeros([1,synaptic_shape[2]],dtype=tf.float32)],axis=0),axis=0)

In [32]:
correction_mat

<tf.Tensor: id=525, shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [0., 0., 0.]]], dtype=float32)>

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [54]:
batch=2
delay=4
n=3
m=2

In [53]:
S=np.zeros((batch,delay,n,m))

In [41]:
def _get_2D_input_spike(S,spike,delay_tensor,depth):
    """input - 
    S : a 4D tensor with batch x delay x n x m ,
    spike: a 2D tensor batch x n, 
    delay_tensor : a 2D tensor n x m
    depth : scalar representing maximum delay 
    
    outputs a tensor with size batch x output_size, where outputsize is twice the size of thresholds_size
    """
    # roll S and get new input,
    S_update=tf.roll(S,shift=-1,axis=1)
    new_input=S_update[:,0,:]
    synaptic_shape=tf.shape(S)
    # add new spikes to S
    correction_mat=tf.expand_dims(tf.concat([tf.ones([synaptic_shape[1]-1,synaptic_shape[2],synaptic_shape[3]],tf.float32),tf.zeros([1,synaptic_shape[2],synaptic_shape[3]],dtype=tf.float32)],axis=0),axis=0)

    S_cut=tf.multiply(S,correction_mat)
    # add spikes to S_cut
    spike_temp=tf.expand_dims(tf.expand_dims(tf.cast(spike,tf.float32),axis=-2),axis=-2)
    delay_tensor_temp=tf.one_hot(tf.cast(tf.multiply(delay_tensor,spike),tf.int32),depth=depth,axis=1)
    spike_tensor=tf.multiply(spike_temp,delay_tensor_temp)
    # update S and return output
    S_out=tf.add(S_cut,spike_tensor)
    return S_out, new_input



In [42]:
synaptic_shape=S.shape

In [67]:
x=tf.constant((np.array([[1,1],[1,0]])))


<tf.Tensor: id=1464, shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [68]:
delay=np.array([[1,0],[3,2],[1,4]])
delay

array([[1, 0],
       [3, 2],
       [1, 4]])

In [71]:
delay_mat=tf.einsum('uv,nv->nuv',tf.constant(delay),x)
delay_mat

<tf.Tensor: id=1594, shape=(2, 3, 2), dtype=int64, numpy=
array([[[1, 0],
        [3, 2],
        [1, 4]],

       [[1, 0],
        [3, 0],
        [1, 0]]])>

In [72]:
tf.one_hot(delay_mat,depth=4,axis=1)

<tf.Tensor: id=1622, shape=(2, 4, 3, 2), dtype=float32, numpy=
array([[[[0., 1.],
         [0., 0.],
         [0., 0.]],

        [[1., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 1.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]]],


       [[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[1., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]]]], dtype=float32)>

In [47]:
x_temp=tf.expand_dims(tf.expand_dims(tf.cast(x,tf.float32),axis=-2),axis=-2)
x_temp

<tf.Tensor: id=948, shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[1., 0.]]]], dtype=float32)>

In [48]:
S_new=tf.multiply(x_temp,tf.one_hot(delay_mat,depth=4,axis=1))
S_new

<tf.Tensor: id=974, shape=(1, 4, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[1., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]]]], dtype=float32)>

In [49]:
S_update=tf.roll(S_new,shift=-1,axis=1)
S_update

<tf.Tensor: id=998, shape=(1, 4, 3, 2), dtype=float32, numpy=
array([[[[1., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [50]:
new_input=S_update[:,0,:]
new_input

<tf.Tensor: id=1023, shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 0.],
        [0., 0.],
        [1., 0.]]], dtype=float32)>

In [51]:
synaptic_shape=tf.shape(S_new)
synaptic_shape

<tf.Tensor: id=1045, shape=(4,), dtype=int32, numpy=array([1, 4, 3, 2], dtype=int32)>

In [89]:
correction_mat=tf.expand_dims(tf.concat([tf.ones([synaptic_shape[1]-1,synaptic_shape[2],synaptic_shape[3]],tf.float32),tf.zeros([1,synaptic_shape[2],synaptic_shape[3]],dtype=tf.float32)],axis=0),axis=0)


<tf.Tensor: id=732, shape=(1, 4, 3, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [91]:
S_cut=tf.multiply(S_update,correction_mat)
S_cut

<tf.Tensor: id=787, shape=(1, 4, 3, 2), dtype=float32, numpy=
array([[[[1., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
from tensorflow.python.util import nest
from tensorflow.python.ops import variable_scope as vs
_TENSOR_VARIABLE_NAME='kernel_2D'
def _tensor_linear(args,
            output_size,
            bias=False,
            bias_initializer=None,
            kernel_initializer=None):
  """Linear map: sum_i(args[i] * W[i]), where W[i] is a variable.
  Args:
    args: a 2D Tensor or a list of 2D, batch, n, Tensors.
    output_size: int, second dimension of W[i].
    bias: boolean, whether to add a bias term or not.
    bias_initializer: starting value to initialize the bias
      (default is all zeros).
    kernel_initializer: starting value to initialize the weight.
  Returns:
    A 2D Tensor with shape `[batch, output_size]` equal to
    sum_i(args[i] * W[i]), where W[i]s are newly created matrices.
  Raises:
    ValueError: if some of the arguments has unspecified or wrong shape.
  """
  if args is None or (nest.is_sequence(args) and not args):
    raise ValueError("`args` must be specified")
  if not nest.is_sequence(args):
    args = [args]

  # Calculate the total size of arguments on dimension 1.
  total_arg_size = 0
  shapes = [a.get_shape() for a in args]
  for shape in shapes:
    if shape.ndims != 3:
      raise ValueError("tensor linear is expecting 3D arguments: %s" % shapes)
    if shape.dims[-1].value is None:
      raise ValueError("linear expects shape[2] to be provided for shape %s, "
                       "but saw %s" % (shape, shape[-1]))
    else:
      total_arg_size += shape.dims[-1].value

  dtype = [a.dtype for a in args][0]

  # Now the computation.
  scope = vs.get_variable_scope()
  with vs.variable_scope(scope) as outer_scope:
    weights = vs.get_variable(
        _TENSOR_VARIABLE_NAME, [output_size, total_arg_size],
        dtype=dtype,
        initializer=kernel_initializer)
    if len(args) == 1:
      res = tf.reduce_sum(tf.multiply(weights,args[0]),axis=-1)
    else:
      res = tf.reduce_sum(tf.multiply(weights,array_ops.concat(args, -1)),axis=-1)
    if not bias:
      return res
    with vs.variable_scope(outer_scope) as inner_scope:
      inner_scope.set_partitioner(None)
      if bias_initializer is None:
        bias_initializer = init_ops.constant_initializer(0.0, dtype=dtype)
      biases = vs.get_variable(
          _BIAS_VARIABLE_NAME, [output_size],
          dtype=dtype,
          initializer=bias_initializer)
    return nn_ops.bias_add(res, biases)

In [38]:
_tensor_linear(new_input,3)

<tf.Tensor: id=744, shape=(1, 3), dtype=float32, numpy=array([[0.41732073, 0.        , 0.73945963]], dtype=float32)>

In [34]:
new_input

<tf.Tensor: id=81, shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 0.],
        [0., 0.],
        [1., 0.]]], dtype=float32)>

In [35]:
kernel_2D

NameError: name 'kernel_2D' is not defined

In [36]:
 weights = vs.get_variable(
        _TENSOR_VARIABLE_NAME, [3, 2],
        dtype=tf.float32)

In [37]:
weights


<tf.Variable 'kernel_2D:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.39672112,  0.76382565],
       [-0.79841745,  0.8517103 ],
       [-0.8448924 ,  1.011239  ]], dtype=float32)>

In [30]:
tf.multiply(weights,new_input)

<tf.Tensor: id=528, shape=(1, 3, 2), dtype=float32, numpy=
array([[[-0.8342153 , -0.        ],
        [ 0.        , -0.        ],
        [-0.12256187, -0.        ]]], dtype=float32)>

In [4]:
def _delay_one_hot_initializer(shape,dtype=None,partition_info=None,verify_shape=None, max_val=2):
    if dtype is None:
        dtype=tf.float32
    return tf.one_hot(tf.random_uniform(shape,0,max_val+1,dtype=tf.int32),depth=max_val+1)
    #return tf.one_hot(tf.zeros(shape,dtype=tf.int32),depth=max_val)
    #return tf.cast(2*tf.ones(shape,dtype=tf.int32),dtype)

In [94]:
g=tf.get_variable('g',shape=[4,3],initializer=_delay_one_hot_initializer)

In [85]:
tf.reduce_sum(g,axis=2)


<tf.Tensor: id=1142, shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [39]:
tf.random_uniform(shape,0,max_val+1,dtype=tf.int32)

<tf.Tensor: id=263, shape=(3, 3), dtype=int32, numpy=
array([[2, 0, 1],
       [2, 1, 2],
       [2, 0, 0]], dtype=int32)>

In [42]:
b=tf.one_hot(a,depth=3)
b

<tf.Tensor: id=298, shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]],

       [[0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.]]], dtype=float32)>

In [81]:
w=tf.random_normal(shape=[4,3])
w

<tf.Tensor: id=1046, shape=(4, 3), dtype=float32, numpy=
array([[-1.2396913 , -0.3139113 , -0.24704355],
       [ 0.78403956, -0.7245917 ,  1.3794924 ],
       [ 0.02887853, -0.42368838,  0.10573038],
       [-0.7269855 , -1.6107087 ,  0.3004246 ]], dtype=float32)>

In [86]:
wd=tf.einsum('un,unv->unv',w,g)

In [87]:
wd

<tf.Tensor: id=1170, shape=(4, 3, 3), dtype=float32, numpy=
array([[[-0.        , -0.        , -1.2396913 ],
        [-0.3139113 , -0.        , -0.        ],
        [-0.        , -0.24704355, -0.        ]],

       [[ 0.        ,  0.78403956,  0.        ],
        [-0.        , -0.7245917 , -0.        ],
        [ 0.        ,  0.        ,  1.3794924 ]],

       [[ 0.        ,  0.02887853,  0.        ],
        [-0.42368838, -0.        , -0.        ],
        [ 0.        ,  0.        ,  0.10573038]],

       [[-0.        , -0.        , -0.7269855 ],
        [-0.        , -0.        , -1.6107087 ],
        [ 0.        ,  0.3004246 ,  0.        ]]], dtype=float32)>

In [91]:
spikes=tf.cast(tf.random_uniform(shape=[1,3,3],minval=0,maxval=2,dtype=tf.int32),tf.float32)
spikes

<tf.Tensor: id=1280, shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 1., 0.],
        [1., 1., 1.],
        [0., 0., 0.]]], dtype=float32)>

In [93]:
w

<tf.Tensor: id=1046, shape=(4, 3), dtype=float32, numpy=
array([[-1.2396913 , -0.3139113 , -0.24704355],
       [ 0.78403956, -0.7245917 ,  1.3794924 ],
       [ 0.02887853, -0.42368838,  0.10573038],
       [-0.7269855 , -1.6107087 ,  0.3004246 ]], dtype=float32)>

In [92]:
tf.einsum('unv,pnv->up',spikes,wd)

<tf.Tensor: id=1309, shape=(1, 4), dtype=float32, numpy=
array([[-0.3139113 ,  0.05944788, -0.39480984, -1.6107087 ]],
      dtype=float32)>

<tf.Tensor: id=431, shape=(4, 4), dtype=float32, numpy=
array([[-0.59065473,  1.1486787 , -1.0515604 ,  1.7172953 ],
       [-0.59518284,  0.98360944, -0.51066786, -2.7135394 ],
       [-0.01143678,  0.91597027, -0.21074538,  1.2811371 ],
       [-0.82938164,  0.36550024, -0.38082522,  1.6179453 ]],
      dtype=float32)>

In [69]:
tf.reduce_sum(w,axis=1)

<tf.Tensor: id=769, shape=(4,), dtype=float32, numpy=array([ 1.2237588 , -2.8357806 ,  1.9749253 ,  0.77323866], dtype=float32)>

In [2]:
batch=2
num_hidden=3
num_inputs=2
delays=3 # max val=2 


In [5]:
delay_tensor=tf.get_variable('g',shape=[3,2],initializer=_delay_one_hot_initializer)
delay_tensor

<tf.Variable 'g:0' shape=(3, 2, 3) dtype=float32, numpy=
array([[[0., 0., 1.],
        [0., 1., 0.]],

       [[0., 0., 1.],
        [1., 0., 0.]],

       [[0., 0., 1.],
        [1., 0., 0.]]], dtype=float32)>

In [6]:
w=tf.random_normal(shape=[num_hidden,num_inputs])
w

<tf.Tensor: id=23, shape=(3, 2), dtype=float32, numpy=
array([[-0.45084414,  0.64287966],
       [ 0.45809525,  0.7257027 ],
       [-0.8971915 , -1.0059435 ]], dtype=float32)>

In [13]:
wd=tf.einsum('un,unv->unv',w,delay_tensor)
wd

<tf.Tensor: id=108, shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.        , -0.        , -0.45084414],
        [ 0.        ,  0.64287966,  0.        ]],

       [[ 0.        ,  0.        ,  0.45809525],
        [ 0.7257027 ,  0.        ,  0.        ]],

       [[-0.        , -0.        , -0.8971915 ],
        [-1.0059435 , -0.        , -0.        ]]], dtype=float32)>

In [11]:
spikes=tf.cast(tf.random_uniform(shape=[batch,num_inputs,delays],minval=0,maxval=2,dtype=tf.int32),tf.float32)
spikes

<tf.Tensor: id=85, shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [1., 0., 1.]],

       [[1., 1., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [12]:
tf.einsum('unv,pnv->up',spikes,wd)

<tf.Tensor: id=97, shape=(2, 3), dtype=float32, numpy=
array([[ 0.       ,  0.7257027, -1.0059435],
       [ 0.       ,  0.       ,  0.       ]], dtype=float32)>

In [120]:
tf.roll(spikes,shift=-1, axis=-1)

<tf.Tensor: id=2048, shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 1.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [0., 1., 1.]]], dtype=float32)>

In [122]:
synaptic_shape=tf.shape(spikes)

In [126]:
correction_mat=tf.expand_dims(tf.concat([tf.ones([synaptic_shape[1],synaptic_shape[2]-1],tf.float32),tf.zeros([synaptic_shape[1],1],dtype=tf.float32)],axis=1),axis=0)

In [127]:
correction_mat

<tf.Tensor: id=2315, shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 0.],
        [1., 1., 0.]]], dtype=float32)>

In [129]:
S_cut=tf.multiply(spikes,correction_mat)
S_cut

<tf.Tensor: id=2396, shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.]],

       [[0., 1., 0.],
        [1., 0., 0.]]], dtype=float32)>

In [130]:
spike=tf.cast(tf.random_uniform(shape=[batch,num_inputs],minval=0,maxval=2,dtype=tf.int32),tf.float32)

In [131]:
spike

<tf.Tensor: id=2430, shape=(2, 2), dtype=float32, numpy=
array([[0., 1.],
       [1., 1.]], dtype=float32)>

In [135]:
tf.concat([S_cut,tf.expand_dims(spike,axis=-1)],axis=-1)

<tf.Tensor: id=2594, shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 1.]],

       [[0., 1., 0., 1.],
        [1., 0., 0., 1.]]], dtype=float32)>

In [144]:
split2,_ = tf.split(S_cut, [-1, 1], -1)

In [145]:
split2

<tf.Tensor: id=2914, shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 0.],
        [0., 1.]],

       [[0., 1.],
        [1., 0.]]], dtype=float32)>

In [147]:
S_out=tf.concat([split2,tf.expand_dims(spike,axis=-1)],axis=-1)

In [148]:
S_out

<tf.Tensor: id=3023, shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 1.]],

       [[0., 1., 1.],
        [1., 0., 1.]]], dtype=float32)>

In [13]:
def _lsnn_weight_initializer(shape,dtype=None,partition_info=None,verify_shape=None, gain=0.5):
    if dtype is None:
        dtype=tf.float32
    #extract second dimension
    W_rec=tf.divide(gain*tf.random_normal(shape=[shape[0],shape[0]],mean=0,stddev=1,dtype=dtype),tf.sqrt(tf.cast(shape[1],tf.float32)))
    new_shape=[shape[0],shape[1]-shape[0]]

    W_in = tf.divide(gain*tf.random_normal(shape=new_shape,mean=0,stddev=1,dtype=dtype),tf.sqrt(tf.cast(new_shape[0],tf.float32)))
    #W_in=tf.random_normal(new_shape,mean=0,stddev=0.001)
    return tf.concat([W_in,W_rec],axis=1)

In [14]:
delay_tensor=tf.get_variable('g',shape=[2,3],initializer=_lsnn_weight_initializer)

In [15]:
delay_tensor

<tf.Variable 'g:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.36764896,  0.20081498,  0.34533864],
       [-0.10750882,  0.4148495 , -0.06166827]], dtype=float32)>